### PR TITLE
Fix decoding of non-ASCII filenames and security issue

### LINKED ISSUE #76: Ver7.2.10 not support chinese file name(maybe east-asia font)
**Describe the bug**
for example, the orginal file name is "Python编程入门 第3版.pdf",  in XDM "NEW DOWNLOAD" window, it appera as "Pythonç¼ç¨å¥é¨  ç¬¬3ç.pdf" 

**To Reproduce**
1. Go to 'https://tc5.us/file/17342680-312078666'
2. At left corner in this page, you can find word in chinese "普通下载", 
3. below this word, a button named "立即下载“ 。click this button
4. If XDM is running and monitoring browser,  the "NEW DOWNLOAD" dialog will pop up , you can find the incorrent file name in File box. It appears "Pythonç¼ç¨å¥é¨  ç¬¬3ç.pdf" 

**Expected behavior**
I want XDM support chinese file name ,maybe east-asia language  has the same issue.

**Screenshots**

**please complete the following information:**
 - OS: Windows7 x64
 - Browser: Firefox 
 - XDM addon Version : not sure, up to date 
 - XDM Version: App version 7.2.10 with runtime 11.0.6

**Generated log using below method**

**Additional context**

### LINKED ISSUE #110: Download the Chinese file, the file name will be garbled.
Download the Chinese file, the file name will be garbled.

### LINKED ISSUE #143: Download garbled characters with non-English characters
image

Download garbled characters with non-English characters. For example, if I download a file with a Chinese file name, it will be garbled after downloading.

### LINKED ISSUE #232: A little bug
Hello,
I found a problem，when I downloaded a file/docement from this [page](https://www.cnki.net/  ) with XDM ，its name will be a messy code,
PS. The docement's name is chinese. But the name of docement downloaded  was messy code.
--------------THX ,

### LINKED ISSUE #308: Problem with filename character encoding
Even with filenames not containing any unusual characters, XDM replaces some chars with weird symbols:

kép
kép

 - OS: Windows 10
 - Firefox
 - XDM addon Version 2.1
 - XDM Version 7.2.11

### LINKED ISSUE #358: Show Arabic file names in strange symbols!
When downloading files with Arabic names, they always appear as strange symbols!
But the files work without problems.

**Screenshots**
https://k.top4top.io/p_17403z1rv1.jpg

 - OS: [Windows 10 pro Build 18363 64-bit Arabic]
 - Browser: [chrome v85.0.4183.121 64-bit]
 - XDM addon Version: [2.1]
 - XDM Version: [7.2.11]

### LINKED ISSUE #387: With  garbled
image

## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

### LINKED ISSUE #430: Accents on file name not working well
When I download a file with accents in spanish like: "¿Qué", downloaded file name is like : "Â¿QuÃ© "

### LINKED ISSUE #448: wrong filenameDecode with Garbled Chinese
**Describe the bug**

here is the response header
image
**youcansee, decode a wrong filename**
image

I would suggest using import java.net.URLDecoder.decode(str, "utf-8"); to decode the name.

### PR DESCRIPTION
**Pull request by objectProgrammer**
Fixes #76
Fixes #110
Fixes #143
Fixes #232
Fixes #308
Fixes #358
Fixes #387
Fixes #430
Fixes #448

The old URL percent-encoding decoder did not support inputs like %C3%AA (which becomes ê) because it assumed all characters to only consist of one percent-sequence. This pull request uses the built-in Java URLDecoder to decode the string and thus fixes that issue.

There was also another problem where the decoded character was not checked, for example %2F becomes / which is not disallowed and might lead to security issues if downloaded from a specially-crafted server.
It now decodes the percents and then checks for illegal characters.

It is worth to note that the Java URLDecoder decodes "+" to " ", so the code encodes the "+" to "%2B" which are then decoded to +.

NOTE: I have tested the decoding code but not in XDM itself, please test it before merging.

### CODE REVIEW

**Comment by alient12** [comment]
I've tested on XDM and it worked successfully . Thanks for fixing .

**Review by AML-MAR5-MDH-sudo — APPROVED** [review]

**Comment by objectProgrammer** [comment]
@subhra74 I saw that you just commented in an issue, can you check this pull request and perhaps merge it? :)

File: app/src/main/java/xdman/util/XDMUtils.java [hunk 1]
```diff
@@ -50,23 +52,16 @@
 	private static final char[] invalid_chars = { '/', '\\', '"', '?', '*', '<',
 			'>', ':', '|' };
 
-	public static String decodeFileName(String str) {
+	public static String decodeFileName(String encoded) {
+		String str = URLDecoder.decode(encoded, StandardCharsets.UTF_8);
```
Comment (subhra74) [inline app/src/main/java/xdman/util/XDMUtils.java]: Please use a fallback so that if URLDecoder throws an exception due to invalid url encoding, we still can decode some of the name using the old way. This happens when some websites uses broken url encoding

**Comment by candrapersada** [comment]
why is the missing file extension, for example [video.mp4](https://cdn15x.cloud9xx.com/user1342/cfd7778f41cb215f90c4f0eee0026827/EP.4.360p.mp4?token=et8rvZaQvE8DFX4qb3bKXg&expires=1608777435&id=105749) changes to _1 without `.mp4`?

**Comment by objectProgrammer** [comment]
@subhra74 Okay, no problem.
@candrapersada Not related to the pull request.

**Comment by candrapersada** [comment]
> @candrapersada Not related to the pull request.

but related to the issues #430

**Comment by objectProgrammer** [comment]
@candrapersada Then write it there, not here. Please delete your messages they are unrelated.

**Comment by objectProgrammer** [comment]
@subhra74 I did it but I'm not sure if it helps much, as the old decoder produces useless information on broken URL-encoding. Honestly I think just using the encoded form as the file name in the case of exception is better but it's not my decision.

File: app/src/main/java/xdman/util/XDMUtils.java (hunk 1 above)
Comment (objectProgrammer) [reply app/src/main/java/xdman/util/XDMUtils.java]: Okay, no problem.

**Comment by jotbyte** [comment]
Maybe he doesn't want to rely on URLDecoder. Maybe to keep it as cross platform and backward compatible as he can. This could also work:

```
public static String decodeFileName(String str) {
		char ch[] = str.toCharArray();
		byte[] bytes = new byte[str.length()];
		for (int i = 0, j=0; i < ch.length; i++, j++) {
			if (ch[i] == '/' || ch[i] == '\\' || ch[i] == '"' || ch[i] == '?'
					|| ch[i] == '*' || ch[i] == '<' || ch[i] == '>'
					|| ch[i] == ':')
				continue;
			if (ch[i] == '%') {
				if ((i + 2) < ch.length) {
					int c = Integer.parseInt(ch[i + 1] + "" + ch[i + 2], 16);
					bytes[j] = (byte) c;
					i += 2;
				}
			} else if (ch[i] == '+'){
				bytes[j] = (byte) ' ';
			} else{
				bytes[j] = (byte) ch[i];
			}
		}
		return new String(bytes, Charset.defaultCharset());
	}
```
Substituted the continue for else ifs and added the special '+' case.

**Comment by objectProgrammer** [comment]
@jotbyte URLDecoder was added in Java 1.2. That was released 1998, there's nothing about backwards compatibility here and there's nothing wrong with using built-in JDK classes. Using URLDecoder is the same as using any other class like for example HashMap. Default charset is not recommended, who said the website is encoding according to the computer? And I don't see the point of manually implementing URL decoding, there is a risk for incorrect decoding (which happened here). And finally, + in the file name should not be converted to space, that is only in URL query parameters (http://example.com/?x=a+b). My solution does all of these correctly and also keeps plus signs. From what I can see, your solution only supports 2 percent characters followed by each other (%C3%AA) and not basic ones like "%2C".

@subhra74 May I ask what's stopping you from merging it?

**Comment by subhra74** [comment]
> @jotbyte URLDecoder was added in Java 1.2. That was released 1998, there's nothing about backwards compatibility here and there's nothing wrong with using built-in JDK classes. Using URLDecoder is the same as using any other class like for example HashMap. Default charset is not recommended, who said the website is encoding according to the computer? And I don't see the point of manually implementing URL decoding, there is a risk for incorrect decoding (which happened here). And finally, + in the file name should not be converted to space, that is only in URL query parameters (http://example.com/?x=a+b). My solution does all of these correctly and also keeps plus signs. From what I can see, your solution only supports 2 percent characters followed by each other (%C3%AA) and not basic ones like "%2C".
> 
> @subhra74 May I ask what's stopping you from merging it?

The PR seems fine, unfortunately I am not getting enough time to review and test it

**Comment by hpp0hpp** [comment]
please help merge this PR, this become a headache for lots of people.

**Comment by jotbyte** [comment]
> My solution does all of these correctly and also keeps plus signs. From what I can see, your solution only supports 2 percent characters followed by each other (%C3%AA) and not basic ones like "%2C".

@objectProgrammer relax mate this isn't a competition. You'll have to remove the security check because it's redundant. It's already done afterwards:

https://github.com/subhra74/xdm/blob/b0532c54cc157fa6e0408cea26dce0f7ba1a352f/app/src/main/java/xdman/util/XDMUtils.java#L95

My implementation is adapted from the same URLDecoder you're using. Why don't you test it out yourself? I'd like to think the computers default charset matters, because of the underlaying filesystem and the language settings. I don't frequently code in vanilla Java, so I'm not sure that's the right way to do it. Remember, the filename is the same name that's shown in the OS with an unknown filesystem and language. @subhra74 what do you think?

**Comment by objectProgrammer** [comment]
@jotbyte Why do you need to implement it yourself when the JDK has a working method for this? You do not encode filenames, Java takes care of all that, you just pass the String. What's getting decoded is the filename sent from the server, which is very unlikely to only include Windows-1252 (default Windows encoding) as that only contains Latin and some extensions. We need to support all languages here. The letter/word "水" becomes "%E6%B0%B4". Decoding that with Windows-1252 is not possible as it does not contain it.

About the double filename check, I'm just fixing decoding here, if I wanted to remove duplicate code calls then the pull request would be named something else.

**Review by subhra74 — APPROVED** [review]

**Comment by jotbyte** [comment]
@objectProgrammer I didn't implement it myself. I studied the URLDecoder and fixed @subhra74's code. Using my code was just a suggestion, I'm not trying to shut down your PR. However, like I said, That security issue (you mentioned also in the title) is already handled in a later function:

> You need to inspect more than just the function you've changed before submitting a pull request. It's already done afterward:
https://github.com/subhra74/xdm/blob/b0532c54cc157fa6e0408cea26dce0f7ba1a352f/app/src/main/java/xdman/util/XDMUtils.java#L95

If you're going to rely on URLDecode, this is all you're gonna need (plus the fallback code):

```java
public static String decodeFileName(String encoded) {
      return URLDecoder.decode(encoded, StandardCharsets.UTF_8);
}
```
the rest is redundant:
```java
                char ch[] = str.toCharArray();
		StringBuffer buf = new StringBuffer();
		for (char c : str.toCharArray()) {
			if (c == '/' || c == '\\' || c == '"' || c == '?'
					|| c == '*' || c == '<' || c == '>'
					|| c == ':')
				continue;
			buf.append(c);
		}
		return buf.toString();
```
The function `createSafeFileName(path)` already deals with the invalid characters. Redundant code makes everything less readable, and that's just the kind of stuff you have to consider. 

Once again, my code was a suggestion (heck even as a less broken fallback path).

**Comment by objectProgrammer** [comment]
@subhra74 Thanks for merging.

@jotbyte Well, if you're right then there was no security issue. But the security code was still incorrect, so I fixed it. If you feel like it, why not open a pull request to remove the redundant code?

**Comment by namv22** [comment]
@subhra74 
Excuse me, but is this fixed in version 7.2.11 yet, or will it be available in the future update?
I seem to encounter the bug of #76 when downloading a Japanese name file

**Comment by subhra74** [comment]
This issue is fixed but not released. Currently I am working on new rewrite of xdm to fix fundamental problems like this. The rewrite will be merged soon to xdm public repo and i am expecting to release beta in October
